import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import '../fonts.dart';

class AppTheme {
  static const ColorScheme lightColorScheme = ColorScheme(
    brightness: Brightness.light,
    primary: Color(0xff30B121),
    onPrimary: Colors.white,
    primaryContainer: Color(0xff70DF63),
    onPrimaryContainer: Color(0xff062303),
    secondary: Color(0xffD9A152),
    onSecondary: Colors.white,
    secondaryContainer: Color(0xffFCD093),
    onSecondaryContainer: Color(0xff362104),
    tertiary: Color(0xffE8B015),
    onTertiary: Colors.white,
    tertiaryContainer: Color(0xffFFEAAE),
    onTertiaryContainer: Color(0xff3D2D00),
    error: Color(0xffFF6400),
    onError: Colors.white,
    errorContainer: Color(0xffFFA972),
    onErrorContainer: Color(0xff552405),
    background: Color(0xffFCFCFC),
    onBackground: Color(0xff1A1B1A),
    surface: Color(0xffF1F1F1),
    onSurface: Color(0xff1A1B1A),
    surfaceVariant: Color(0xffE7E7E7),
    onSurfaceVariant: Color(0xff455344),
    outline: Color(0xffD4D4D4),
    outlineVariant: Color(0xffF1F1F1),
  );

  static const ColorScheme darkColorScheme = ColorScheme(
    brightness: Brightness.dark,
    primary: Color(0xff30B121),
    onPrimary: Color(0xff062303),
    primaryContainer: Color(0xff083803),
    onPrimaryContainer: Color(0xff30B121),
    secondary: Color(0xffD9A152),
    onSecondary: Color(0xff2C1A02),
    secondaryContainer: Color(0xff362104),
    onSecondaryContainer: Color(0xffFCD093),
    tertiary: Color(0xffE8B015),
    onTertiary: Color(0xff332600),
    tertiaryContainer: Color(0xff342700),
    onTertiaryContainer: Color(0xffFFEAAE),
    error: Color(0xffFF6400),
    onError: Color(0xff3B1902),
    errorContainer: Color(0xff502103),
    onErrorContainer: Color(0xffFFA972),
    background: Color(0xff1A1B1A),
    onBackground: Color(0xffFCFCFC),
    surface: Color(0xff222322),
    onSurface: Color(0xffFCFCFC),
    surfaceVariant: Color(0xff333F32),
    onSurfaceVariant: Color(0xffA4A7A3),
    outline: Color(0xff4E4E4E),
    outlineVariant: Color(0xff393939),
  );

  static final ThemeData light = ThemeData(
    useMaterial3: true,
    visualDensity: VisualDensity.adaptivePlatformDensity,
    fontFamily: Fonts.iranSansX,
    brightness: Brightness.light,
    scaffoldBackgroundColor: lightColorScheme.background,
    colorScheme: lightColorScheme,
    textSelectionTheme: TextSelectionThemeData(
      cursorColor: lightColorScheme.primary.withOpacity(0.4),
      selectionColor: lightColorScheme.secondaryContainer,
      selectionHandleColor: lightColorScheme.secondary,
    ),
    appBarTheme: AppBarTheme(
      elevation: 4,
      iconTheme: const IconThemeData(size: 19),
      // titleSpacing: 0,
      backgroundColor: lightColorScheme.surface,
      surfaceTintColor: lightColorScheme.surface,
      shadowColor: Colors.black38,
      titleTextStyle: TextStyle(
        fontSize: 16,
        fontWeight: FontWeight.w800,
        color: lightColorScheme.onSurface,
        fontFamily: Fonts.iranSansX,
      ),
      systemOverlayStyle: const SystemUiOverlayStyle(
        statusBarColor: Colors.transparent,
        statusBarIconBrightness: Brightness.dark,
        statusBarBrightness: Brightness.light,
      ),
    ),
    elevatedButtonTheme: ElevatedButtonThemeData(
      style: ButtonStyle(
        shape: MaterialStateProperty.all(
          RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
        ),
      ),
    ),
    textTheme: TextTheme(
      labelSmall: TextStyle(color: lightColorScheme.onSurfaceVariant),
      labelMedium: TextStyle(color: lightColorScheme.onSurfaceVariant),
      labelLarge: TextStyle(color: lightColorScheme.onSurfaceVariant),
      bodySmall: TextStyle(color: lightColorScheme.onBackground),
      bodyMedium: TextStyle(color: lightColorScheme.onBackground),
      bodyLarge: TextStyle(color: lightColorScheme.onBackground),
      titleSmall: TextStyle(color: lightColorScheme.onBackground),
      titleMedium: TextStyle(color: lightColorScheme.onBackground),
      titleLarge: TextStyle(color: lightColorScheme.onBackground),
      headlineSmall: TextStyle(color: lightColorScheme.onBackground),
      headlineMedium: TextStyle(color: lightColorScheme.onBackground),
      headlineLarge: TextStyle(color: lightColorScheme.onBackground),
      displaySmall: TextStyle(color: lightColorScheme.onBackground),
      displayMedium: TextStyle(color: lightColorScheme.onBackground),
      displayLarge: TextStyle(color: lightColorScheme.onBackground),
    ),
  );

  static final ThemeData dark = ThemeData(
    useMaterial3: true,
    visualDensity: VisualDensity.adaptivePlatformDensity,
    fontFamily: Fonts.iranSansX,
    brightness: Brightness.dark,
    scaffoldBackgroundColor: darkColorScheme.background,
    colorScheme: darkColorScheme,
    textSelectionTheme: TextSelectionThemeData(
      cursorColor: darkColorScheme.primary.withOpacity(0.4),
      selectionColor: darkColorScheme.secondaryContainer,
      selectionHandleColor: darkColorScheme.secondary,
    ),
    appBarTheme: AppBarTheme(
      elevation: 4,
      iconTheme: const IconThemeData(size: 19),
      // titleSpacing: 0,
      backgroundColor: darkColorScheme.surface,
      surfaceTintColor: darkColorScheme.surface,
      shadowColor: darkColorScheme.outlineVariant,
      titleTextStyle: TextStyle(
        fontSize: 16,
        fontWeight: FontWeight.w800,
        color: darkColorScheme.onSurface,
        fontFamily: Fonts.iranSansX,
      ),
      systemOverlayStyle: const SystemUiOverlayStyle(
        statusBarColor: Colors.transparent,
        statusBarIconBrightness: Brightness.light,
        statusBarBrightness: Brightness.dark,
      ),
    ),
    elevatedButtonTheme: ElevatedButtonThemeData(
      style: ButtonStyle(
        shape: MaterialStateProperty.all(
          RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
        ),
      ),
    ),
    textTheme: TextTheme(
      labelSmall: TextStyle(color: darkColorScheme.onSurfaceVariant),
      labelMedium: TextStyle(color: darkColorScheme.onSurfaceVariant),
      labelLarge: TextStyle(color: darkColorScheme.onSurfaceVariant),
      bodySmall: TextStyle(color: darkColorScheme.onBackground),
      bodyMedium: TextStyle(color: darkColorScheme.onBackground),
      bodyLarge: TextStyle(color: darkColorScheme.onBackground),
      titleSmall: TextStyle(color: darkColorScheme.onBackground),
      titleMedium: TextStyle(color: darkColorScheme.onBackground),
      titleLarge: TextStyle(color: darkColorScheme.onBackground),
      headlineSmall: TextStyle(color: darkColorScheme.onBackground),
      headlineMedium: TextStyle(color: darkColorScheme.onBackground),
      headlineLarge: TextStyle(color: darkColorScheme.onBackground),
      displaySmall: TextStyle(color: darkColorScheme.onBackground),
      displayMedium: TextStyle(color: darkColorScheme.onBackground),
      displayLarge: TextStyle(color: darkColorScheme.onBackground),
    ),
  );
}
